[colors]
# Background: Base
background=111c18ff
# Text: Foreground
text=c1c497ff
# Match: Green
match=509475ff
# Selection: Foreground
selection=c1c497ff
# Selection Text: Background
selection-text=111c18ff
# Border: Jade (matches Hyprland active border)
border=71ceadff
