[colors]
# Background: Base
background=191724ff
# Text: Text
text=e0def4ff
# Match: Foam
match=9ccfd8ff
# Selection: Highlight (Med)
selection=403d52ff
# Selection Text: Text
selection-text=e0def4ff
# Border: Love (matches Hyprland active border)
border=eb6f92ff
