[colors]
# Background: Base
background=fffcf0ff
# Text: Foreground
text=100f0fff
# Match: Blue
match=4385beff
# Selection: Surface
selection=cecdc3ff
# Selection Text: Foreground
selection-text=100f0fff
# Border: Blue (matches Hyprland active border)
border=505050ff
