[colors]
# Background: Base
background=2c2525ff
# Text: Foreground
text=e6d9dbff
# Match: Orange
match=f38d70ff
# Selection: Surface
selection=403e41ff
# Selection Text: Foreground
selection-text=e6d9dbff
# Border: Foreground (matches Hyprland active border)
border=e6d9dbff
