# miasma theme for swaylock
font=JetBrainsMono Nerd Font

image=$HOME/.config/omarchy/current/background

ring-color=#78824b
text-color=#c2c2b0
inside-color=#22222230
line-color=#78824b

ring-clear-color=#78824b
text-clear-color=#c2c2b0
inside-clear-color=#222222
line-clear-color=#78824b

key-hl-color=#78824b
