[colors]
# Background: Base
background=1f1f28ff
# Text: Foreground
text=dcd7baff
# Match: Blue
match=7e9cd8ff
# Selection: Wave Blue
selection=2d4f67ff
# Selection Text: Yellow
selection-text=c8c093ff
# Border: Foreground (matches Hyprland active border)
border=dcd7baff
