[colors]
# Background: Base
background=faf4edff
# Text: Text
text=575279ff
# Match: Pine
match=56949fff
# Selection: Highlight (Low)
selection=dfdad9ff
# Selection Text: Text
selection-text=575279ff
# Border: Text (matches Hyprland active border)
border=575279ff
