[colors]
# Background: Base
background=121212ff
# Text: Foreground
text=bebebeff
# Match: Orange
match=e68e0dff
# Selection: Surface
selection=333333ff
# Selection Text: Foreground
selection-text=bebebeff
# Border: Grey (matches Hyprland active border)
border=8a8a8dff
