[colors]
# Background: Base
background=2e3440ff
# Text: Foreground
text=d8dee9ff
# Match: Blue
match=81a1c1ff
# Selection: Polar Night highlight
selection=4c566aff
# Selection Text: Foreground
selection-text=d8dee9ff
# Border: Niri active border
border=d8dee9ff
