[colors]
# Background: Base
background=0b0c16ff
# Text: Foreground
text=ddf7ffff
# Match: Blue
match=829dd4ff
# Selection: Surface
selection=6a6e95ff
# Selection Text: Foreground
selection-text=ddf7ffff
# Border: Green (matches Hyprland active border)
border=26a269ff
