[colors]
# Background: Dark Hard Base
background=2d353bff
# Text: Foreground
text=d3c6aaff
# Match: Blue
match=7fbbb3ff
# Selection: Surface 1
selection=475258ff
# Selection Text: Foreground
selection-text=d3c6aaff
# Border: Foreground (matches Hyprland active border)
border=d3c6aaff
