# vantablack theme for swaylock
font=JetBrainsMono Nerd Font

image=$HOME/.config/omarchy/current/background

ring-color=#8d8d8d
text-color=#ffffff
inside-color=#0d0d0d30
line-color=#8d8d8d

ring-clear-color=#8d8d8d
text-clear-color=#ffffff
inside-clear-color=#0d0d0d
line-clear-color=#8d8d8d

key-hl-color=#ffffff
