# white theme for swaylock
font=JetBrainsMono Nerd Font

image=$HOME/.config/omarchy/current/background

ring-color=#6e6e6e
text-color=#000000
inside-color=#ffffff30
line-color=#6e6e6e

ring-clear-color=#6e6e6e
text-clear-color=#000000
inside-clear-color=#ffffff
line-clear-color=#6e6e6e

key-hl-color=#1a1a1a
