[colors]
# Background: Base
background=060b1eff
# Text: Foreground
text=ffceadff
# Match: Blue
match=7d82d9ff
# Selection: Surface
selection=6d7db6ff
# Selection Text: Foreground
selection-text=ffceadff
# Border: Blue (matches Hyprland active border)
border=4e85d8ff
